version: '3.8'
services:
  # mongodb
  mongodb:
    image:  mongo:4.4
    container_name: mongodb
    restart:  always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpassword
      AUTH: admin
    ports:
      - '27017:27017'
    volumes:
      - 'my_mongodb_data:/data/db'
  # mongo express
  mongo-express:
    image:  mongo-express:0.54.0
    container_name: mongo-express
    restart:  always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpassword
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - '8081:8081'
    depends_on:
      - mongodb


volumes:
  my_mongodb_data:
    driver: local